# Generated by Django 3.2.15 on 2023-10-04 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptext', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clip',
        ),
    ]
