# Generated by Django 3.2.15 on 2023-10-05 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0003_audiofile_imagemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageModel',
            new_name='ImageFile',
        ),
    ]
