# Generated by Django 3.2.15 on 2023-10-05 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0005_rename_image_imagefile_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagefile',
            old_name='path',
            new_name='image',
        ),
    ]
