# Generated by Django 3.2.15 on 2023-10-05 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0006_rename_path_imagefile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiofile',
            old_name='title',
            new_name='text',
        ),
    ]
