# Generated by Django 3.2.15 on 2023-10-05 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appmain', '0009_auto_20231005_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clip',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appmain.audiofile'),
        ),
        migrations.AlterField(
            model_name='clip',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appmain.imagefile'),
        ),
        migrations.CreateModel(
            name='VideoClipFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audio/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='clip',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appmain.videoclipfile'),
        ),
    ]
