# Generated by Django 3.2.15 on 2023-10-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0012_alter_imagefile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
