# Generated by Django 3.2.15 on 2023-10-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0014_auto_20231006_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='name',
            field=models.CharField(blank=True, default='None', max_length=255, null=True),
        ),
    ]
