# Generated by Django 3.2.15 on 2023-10-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0015_alter_audiofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='name',
            field=models.CharField(blank=True, default='None', max_length=255, null=True),
        ),
    ]
