# Generated by Django 3.2.15 on 2023-10-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0018_auto_20231006_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
