# Generated by Django 3.2.15 on 2023-10-05 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appvoice', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudioFile',
        ),
    ]
